apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend
  name: saythx-frontend
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: "3000"
    port: 3000
    targetPort: 3000
    nodePort: 32008
  selector:
    app: frontend
  type: {{ .Values.service.type }}
